wiki/encyclopedia/urls.py
from django.urls import path
from . import views

app_name = 'encyclopedia'

urlpatterns = [
     path("", views.index, name="index"),
     path("wiki/<str:title>", views.entry, name="entry"),
     path("modify/<str:title>", views.modify, name="modify"),
     path("search", views.search, name="search"),
     path("topics/", views.topics, name='topics'),
     path("randoms", views.randoms, name="randoms"),
    
     
     
     
 ]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('encyclopedia.urls'))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect

from django.urls import reverse
from django.http import HttpResponseRedirect

from . import util

from django import forms

import re

from markdown2 import Markdown
markdowner = Markdown()

import random



# Create your views here.

class NewSearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia'}))


class NewCreateForm(forms.Form):
    title = forms.CharField(label="Title:", widget=forms.TextInput(attrs={'class': 'form-control w-75 mb-2'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))



def index(request):
    form = NewSearchForm()
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        'form': form
    })

def entry(request, title):
    entries = util.list_entries()
    form = NewSearchForm()
    title = title
    
    return render(request, "encyclopedia/entry.html", {
        "entries": util.get_entry(title),
        "form": form, 
        "title": title
    })

def search(request):

    val = request.GET['q']

    content = util.get_entry(val)

    if content:
        return HttpResponseRedirect(reverse('encyclopedia:entry', args=[val]))
    else:
        entries = util.list_entries()
        subStringEntries = []
        string = re.compile("(?i)(" + val + ")")      # ? Exist or Not 0|1   i# A case insensitive match is performed, meaning capital letters will be matched by non-capital letters and vice versa.
       
        for entry in entries:
            if string.search(entry):
                subStringEntries.append(entry)

        return render(request, "encyclopedia/search.html", {
            "string": val, 
            "subStringEntries": subStringEntries
            })


def topics(request):
    if request.method == "POST":
        # print(request.POST.get('entry'))
        form = NewCreateForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            markdown = form.cleaned_data["content"]
            if util.get_entry(title):
                return render(request, "encyclopedia/error.html", {
                    "form": form,
                    "exists": True,
                    "title": title
                })
            else:
                # entry = form.cleaned_data["entry"]
                # print(entry)
                util.save_entry(title, markdown)
                return redirect('encyclopedia:index')
    else:
            # return render(request, "wiki/topics.html", {
            #     "form": form,
            #     "exists": False
            # })
        return render(request, "encyclopedia/topics.html", {
        "form": NewCreateForm(),
        "exists": False
    })




# 
# 

class ModifyForm(forms.Form):
     body = forms.CharField(label="Modify Body", widget=forms.Textarea(
        attrs={'class': 'form-control', 'cols': '10'}))
    
    
def modify(request, title):
    edform = ModifyForm(initial={'body': util.get_entry(title)})
    if request.method == "POST":
        modifyform = ModifyForm(request.POST)
        if modifyform.is_valid():
            # title = modifyform.cleaned_data.get("title")
            # newcontent = modifyform.cleaned_data.get("body")
            newcontent = modifyform.cleaned_data["body"]
            # saving the new content
            util.save_entry(title, newcontent)
            # form = NewSearchForm()
            # htmlcontent = markdowner.convert(newcontent)
            # return render(request, "wiki/modify.html", {
            #     "title": title, "content": htmlcontent, "form": form
            # })
            # return redirect(request, "wiki:index", {
            #     "title": title, "newcontent": htmlcontent
            # })
            return HttpResponseRedirect(reverse('encyclopedia:entry', args=[title]))
    else:
        # form = NewSearchForm()
        # modifyform = ModifyForm({"title": title, "newcontent": util.get_entry(title)})
        # return render(request, "wiki/modify.html", {"form": form, "modifyform": modifyform})
        # return redirect(request, "wiki:page", {"form": form, "modifyform": modifyform})
        # return render(request, "wiki/modify.html", {"title": title, "newcontent": util.get_entry(title)})
        return render(request, "encyclopedia/modify.html", {"title": title, "edform":edform})
    

def randoms(request):
    entries = util.list_entries()
    num = len(entries)
    # generating a random number for the entry
    entry = random.randint(0, num-1)
    title = entries[entry]
    mdcontent = util.get_entry(title)
    htmlcontent = markdowner.convert(mdcontent)
    form = NewSearchForm()
    return render(request, "encyclopedia/randoms.html", {"form": form, "title": title, "content": htmlcontent})

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% load markdown_extras %}

{% block title %}
Encyclopedia
{% endblock %}

{% block content %}
<div class="container">

 {% if entries %}
  <p>{{ entries | markdown | safe }}</p>

    <a href="{% url 'encyclopedia:modify' title %}">
        <i class="fa fa-edit fa-x " ></i> 
        Edit
    </a>
 
{% else %}
<div class="error">
    <h1 >Sorry  </h1>

    <h2  > 404 - Your requested page cannot be found</h2>  

    <h4>Wiki does not have an article with this name</h4>
</div>
{% endif %}


</div>

{%endblock%}
<hr>

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    ERROR
{% endblock %}
{% load static %}
{% block content %}
    <h1>ERROR</h1>

    <div class="container">
        {{content}}

        <div class="error2" style="margin-top: 40px;"  >
           
            </div>
            <a href="{% url 'encyclopedia:topics' %}">Create New Page</a>    
    </div>
    
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% load markdown_extras %}

{% block title %}
    Encyclopedia
{% endblock %}




{% block content %}

    <h1>All Pages</h1>
 <div class="container">

    <ul>
        {% for entry in entries %}
        <a href="wiki/{{entry }}"><li>{{ entry | markdown | safe  }}</li>
        </a>
        {% endfor %}
    </ul>
</div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

{% load markdown_extras %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
    {% block body %}


    <div class="container">
            <nav class="navbar  navbar-dark bg-primary">
           
               
                    <a class="navbar-brand" href="{% url 'encyclopedia:index' %}">Django Home</a>
                
            </nav>
            
            <div class="row">
                <div class="sidebar col-lg-3 col-md-4">
                    <img class="img-fluid w-50 text-center mx-5 mb-2" src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Wikipedia_logo_%28svg%29.svg/1250px-Wikipedia_logo_%28svg%29.svg.png" alt="Wiki logo">

                    <img class="img-fluid text-center" src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Wikipedia-logo-textonly.svg/200px-Wikipedia-logo-textonly.svg.png" alt="">
                    <!-- <h2>Wiki</h2> -->
                    <!-- <form action="wiki/index">
                        <input class="search" type="text" name="" placeholder="Search Encyclopedia">
                    </form> -->
                     <form action="{% url 'encyclopedia:search' %}" >
                        {% csrf_token %}
                        <div class="input-group mb-3 mx-2">
                            <input type="text" class="form-control search" name="q" placeholder="Search Encyclopedia" aria-label="Search Encyclopedia" aria-describedby="button-addon2" required>
                                <div class="input-group-append">
                                <input type="Submit" class="btn btn-secondary mb-4 ml-2" value="Go"/>
                                </div>
                        </div>
                    </form>
                    <div>
                        <a href="{% url 'encyclopedia:index' %}">Home</a>
                    </div>
                    <div>
                        <a href="{% url 'encyclopedia:topics' %}">Create New Page</a>
                    </div>
                    <!-- <div>
                        Random Page
                    </div> -->
                    <div>
                        <a href="{% url 'encyclopedia:randoms' %}">Random Page</a>
                    </div>
                    {% block nav %}
                    {% endblock %}
                </div>

                <div class="main col-lg-9 col-md-8">
                <div class="row">
                <div class="main col-lg-8 col-md-8 pl-3">
                {% block content %}
                {% endblock %}
                </div>
                <div class="sidebar left col-lg-4 col-md-4">
                   <img class="img-fluid w-50 text-center mx-5 mb-2" src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Wikipedia_logo_%28svg%29.svg/1250px-Wikipedia_logo_%28svg%29.svg.png" alt="Wiki logo"/>

                   <img class="img-fluid text-center mb-4" src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Wikipedia-logo-textonly.svg/200px-Wikipedia-logo-textonly.svg.png" alt=""/>
               
                    <ul class="nav flex-column">
                    <li>Type of site  <span>online cs50</span></li>
                    <li>Country of <span>Egypt</span></li>
                    <li>Design by <span>Fawzy Astafanous</span></li>
                    </ul>

                </div>
                </div>
                </div>
        </div>
    </div>
    {% endblock %}

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/modify.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block content %}

    <div>
        
        <form action="{% url 'encyclopedia:modify' title %}" method="POST">
            {% csrf_token %}
            {{edform}}
            <input type="Submit" class="btn btn-primary mt-3" value="Submit"/>
        </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/randoms.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}

    <div class="container">
        {{ content | safe }}
    </div>

    <a href="{% url 'encyclopedia:modify' title %}">
        <i class="fa fa-edit fa-x " ></i> 
        Edit
    </a>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block content %}
<div class="container">
    <h1>Searching for "{{ string }}":</h1>
    <ul>
        {% for subStringEntry in subStringEntries %}
            <li class="mb-2"><a href="{% url 'encyclopedia:entry' subStringEntry %}">{{subStringEntry}}</a></li>
        {% empty %}
            No results found
        {% endfor %}
    </ul>
 </div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/task.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}

    <div class="container">
        {{ content | safe }}
    </div>
    
    <a href="{% url 'encyclopedia:modify' title %}"><i class="fa fa-edit fa-x " ></i> 
        Edit
    </a>
    
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/topics.html
{% extends "encyclopedia/layout.html" %}

{% load markdown_extras %}

{% block body %}
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'encyclopedia:index' %}">Django Home</a>
    </div>
  </nav>
  <h2 style="text-align: center; padding: 50px;">New Topic</h2>
  <div class="container col-lg-6 ">
<form class="entry-form" action="{% url 'encyclopedia:topics' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    {% if exists %}
    {% comment %} <p class="alert alert-danger">Entry '{{ title }}' already exists.</p> {% endcomment %}
    {% endif %} 
    <input type="submit" class="btn btn-primary mt-3" value="Save"> 
</form>



{% endblock %}